version: '3.8'

services:
  api:
    build: .
    container_name: user-api
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=http://localhost:8000
      - LOG_LEVEL=INFO
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tests:
    build: .
    container_name: user-api-tests
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
      - TEST_DATA_PATH=data/test_data.json
      - LOG_LEVEL=INFO
    volumes:
      - ./tests:/app/tests
      - ./reports:/app/reports
      - ./logs:/app/logs
    command: pytest tests/ -vv --html=reports/html/report.html --self-contained-html